---
# travis-ci config for pipdeptree

language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
addons:
  apt:
    packages:
      - graphviz
before_install:
  - pip install -U pip>=8.0.2
  - pip install graphviz
  - make test-env
install: pip install .
script: py.test -v
after_script: make clean clean-env
sudo: false
